services:
  portfolio:
    image: ghcr.io/aust-1/portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"

      # Domaine racine
      - "traefik.http.routers.portfolio.rule=Host(`eliott-roussille.fr`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"

      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

      # Optionnel: www -> non-www
      - "traefik.http.routers.portfolio-www.rule=Host(`www.eliott-roussille.fr`)"
      - "traefik.http.routers.portfolio-www.entrypoints=websecure"
      - "traefik.http.routers.portfolio-www.tls.certresolver=myresolver"
      - "traefik.http.routers.portfolio-www.middlewares=portfolio-redirect-www@docker"
      - "traefik.http.middlewares.portfolio-redirect-www.redirectregex.regex=^https://www\\.(.*)"
      - "traefik.http.middlewares.portfolio-redirect-www.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.portfolio-redirect-www.redirectregex.permanent=true"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
